"""make_sku_barcode_unique_per_business

Revision ID: 113faffd3aec
Revises: a8529711f1b1
Create Date: 2026-07-22 19:53:59.389592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113faffd3aec'
down_revision: Union[str, None] = 'a8529711f1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    op.create_unique_constraint('uq_product_business_barcode', 'products', ['business_id', 'barcode'])
    op.create_unique_constraint('uq_product_business_sku', 'products', ['business_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_business_sku', 'products', type_='unique')
    op.drop_constraint('uq_product_business_barcode', 'products', type_='unique')
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    # ### end Alembic commands ###
