"""add notes to suppliers

Revision ID: 1e7a772e39f7
Revises: 113faffd3aec
Create Date: 2026-07-30 02:08:14.966362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7a772e39f7'
down_revision: Union[str, None] = '113faffd3aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    # ### end Alembic commands ###
