"""add_returns_and_return_items

Revision ID: 64628da45cce
Revises: 4185af9bbd50
Create Date: 2026-07-15 22:59:05.472341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64628da45cce'
down_revision: Union[str, None] = '4185af9bbd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('processed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('return_type', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('refund_method', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_refund', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_index(op.f('ix_returns_business_id'), 'returns', ['business_id'], unique=False)
    op.create_table('return_items',
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('sale_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('selling_unit_id', sa.UUID(), nullable=True),
    sa.Column('selling_unit_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('base_unit_quantity_used', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('refund_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sale_items', sa.Column('returned_quantity', sa.DECIMAL(precision=12, scale=3), nullable=False, server_default='0.000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'returned_quantity')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_returns_business_id'), table_name='returns')
    op.drop_table('returns')
    # ### end Alembic commands ###
