"""add_max_discount_to_settings

Revision ID: 8854db6a5086
Revises: 9d185525eb86
Create Date: 2026-07-16 00:08:34.789716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8854db6a5086'
down_revision: Union[str, None] = '9d185525eb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column('max_discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_settings', 'max_discount_percent')
    # ### end Alembic commands ###
