"""initial_schema

Revision ID: 94bb656280ff
Revises: 
Create Date: 2026-07-13 00:44:24.885866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bb656280ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_action', table_name='activity_logs')
    op.drop_index('idx_activity_business', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_business_id'), 'activity_logs', ['business_id'], unique=False)
    op.drop_index('idx_audit_business', table_name='audit_logs')
    op.drop_index('idx_audit_target', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.drop_index('ix_selling_units_barcode', table_name='selling_units')
    op.drop_index('ix_selling_units_display_order', table_name='selling_units')
    op.drop_index('ix_selling_units_name', table_name='selling_units')
    op.drop_index('ix_selling_units_sku', table_name='selling_units')
    op.drop_index('idx_stock_movements_business', table_name='stock_movements')
    op.drop_index('idx_stock_movements_product', table_name='stock_movements')
    op.drop_index('idx_stock_movements_reference', table_name='stock_movements')
    op.drop_index('idx_stock_movements_type', table_name='stock_movements')
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.create_index('idx_stock_movements_type', 'stock_movements', ['movement_type'], unique=False)
    op.create_index('idx_stock_movements_reference', 'stock_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_stock_movements_product', 'stock_movements', ['product_id'], unique=False)
    op.create_index('idx_stock_movements_business', 'stock_movements', ['business_id'], unique=False)
    op.create_index('ix_selling_units_sku', 'selling_units', ['sku'], unique=False)
    op.create_index('ix_selling_units_name', 'selling_units', ['name'], unique=False)
    op.create_index('ix_selling_units_display_order', 'selling_units', ['display_order'], unique=False)
    op.create_index('ix_selling_units_barcode', 'selling_units', ['barcode'], unique=False)
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.create_index('idx_audit_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_audit_business', 'audit_logs', ['business_id'], unique=False)
    op.drop_index(op.f('ix_activity_logs_business_id'), table_name='activity_logs')
    op.create_index('idx_activity_business', 'activity_logs', ['business_id'], unique=False)
    op.create_index('idx_activity_action', 'activity_logs', ['action'], unique=False)
    # ### end Alembic commands ###
