"""add_discount_type_to_sales

Revision ID: 9d185525eb86
Revises: 64628da45cce
Create Date: 2026-07-15 23:45:52.270029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d185525eb86'
down_revision: Union[str, None] = '64628da45cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount_type', sa.String(length=20), nullable=True))
    op.add_column('sales', sa.Column('discount_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount_reason')
    op.drop_column('sales', 'discount_type')
    # ### end Alembic commands ###
