"""add_auto_print_receipts

Revision ID: a8529711f1b1
Revises: d88d307ac9de
Create Date: 2026-07-21 22:24:41.655373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8529711f1b1'
down_revision: Union[str, None] = 'd88d307ac9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column('auto_print_receipts', sa.Boolean(), nullable=True))
    op.alter_column('business_settings', 'max_discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_settings', 'max_discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.drop_column('business_settings', 'auto_print_receipts')
    # ### end Alembic commands ###
